FROM openjdk:21-jdk-slim-bookworm AS app

WORKDIR /opt
RUN apt update && apt install -y tini git --no-install-recommends && rm -rf /var/lib/apt/lists/*
COPY openaev-build ./

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["java", "-jar", "openaev-api.jar"]
